// [vibe]
// Apps Script's editor only runs plain JavaScript (no TypeScript, no ES module import/export),
// so `src/lib/newsletter/template.ts` — the one place the newsletter's HTML/text template is
// defined — can't be pasted into the Sender script as-is. This strips its types (via Node's
// built-in `stripTypeScriptTypes`, so no extra dependency) and `export` keywords, and writes
// the result to .vault/GENERATED_Template.gs (gitignored: it's a build artifact, regenerate it
// whenever template.ts changes) for you to paste into the Sender Apps Script project's
// Template.gs file. See "Keeping the email template in sync" in docs/NEWSLETTER.md for the
// one-time integration and why this isn't just done automatically.
//
// Run with: node scripts/sync-newsletter-template.ts

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { stripTypeScriptTypes } from "node:module";

const SOURCE = "src/lib/newsletter/template.ts";
const OUTPUT = ".vault/GENERATED_Template.gs";

// matches this project's Apps Script convention of a trailing `_` for "private to this script"
const RENAMES: Array<[string, string]> = [
  ["buildNewsletterHtml", "buildNewsletterHtml_"],
  ["buildNewsletterText", "buildNewsletterText_"],
  ["escapeHtml", "escapeHtml_"],
  ["urlsForDomain", "urlsForDomain_"],
];

async function main() {
  const source = await readFile(SOURCE, "utf-8");

  // type-only lines (e.g. `export type Foo = {...};`) come out as blank space, not removed —
  // preserved for source-map fidelity, which we don't need here, so tidy it up below
  const stripped = stripTypeScriptTypes(source, { mode: "strip" });

  let output = stripped
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, "")) // trailing whitespace left by blanked types
    .join("\n")
    .replace(/\n{3,}/g, "\n\n") // collapse the blank runs left by removed `type` blocks
    .replace(/^export /gm, "") // Apps Script has no module system — every export is just global
    .trim();

  for (const [from, to] of RENAMES) {
    // word-boundary so e.g. `escapeHtml` doesn't also match inside `buildNewsletterHtml`
    output = output.replace(new RegExp(`\\b${from}\\b`, "g"), to);
  }

  const banner = `/**
 * GENERATED by scripts/sync-newsletter-template.ts from ${SOURCE} — do not hand-edit.
 * See "Keeping the email template in sync" in docs/NEWSLETTER.md before pasting this in.
 */

`;

  await mkdir(".vault", { recursive: true });
  await writeFile(OUTPUT, banner + output + "\n", "utf-8");

  console.log(`✓ Wrote ${OUTPUT} — paste it into the Sender project's Template.gs`);
}

void main();
